POST http://localhost:8080/scrape
Content-Type: application/json

{
  "url": "https://www.emag.ro",
  "headers": {
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache"
  },
  "timeout": "PT130S"
}