POST http://localhost:8080/scrape
Content-Type: application/json

{
  "url": "https://www.emag.ro/telefon-mobil-apple-iphone-17-pro-max-256gb-5g-deep-blue-mfyp4zd-a/pd/DL99FV3BM/?ref=profiled_categories_home_all_first_ml_1_3&provider=rec&recid=rec_106_ee2a7aebe0407e55a375300d5dad49bde90ba51532871043f353589455d7dbaa_1778927803&scenario_ID=106",
  "headers": {
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache"
  },
  "timeout": "PT130S"
}